### ISSUE TITLE
Failed to add Gmail account

### ISSUE THREAD

**Issue by mrttson** [google/mobly-bundled-snippets#126]
I've tried to add gmail account but some error occurs:

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\SCS\anaconda3\lib\site-packages\mobly-1.9.1-py3.7.egg\mobly\controllers\android_device_lib\jsonrpc_client_base.py", line 355, in rpc_call
    return self._rpc(name, *args)
  File "C:\SCS\anaconda3\lib\site-packages\mobly-1.9.1-py3.7.egg\mobly\controllers\android_device_lib\jsonrpc_client_base.py", line 326, in _rpc
    raise ApiError(self._ad, result['error'])
mobly.controllers.android_device_lib.jsonrpc_client_base.ApiError: <AndroidDevice|5200b9494d8c749d>
-------------- Java Stacktrace ---------------
android.accounts.AuthenticatorException: Sign in failed with status UNKNOWN_ERROR
        at android.accounts.AccountManager.convertErrorToException(AccountManager.java:2533)
        at android.accounts.AccountManager.access$700(AccountManager.java:167)
        at android.accounts.AccountManager$AmsTask$Response.onError(AccountManager.java:2369)
        at android.accounts.IAccountManagerResponse$Stub.onTransact(IAccountManagerResponse.java:70)
        at android.os.Binder.execTransact(Binder.java:739)
```

**Comment by xpconanfan** [comment]
Seems like an issue with Android/network?
If you think it's a problem in MBS implementation, please point it out.

**Comment by yiantong** [comment]
i have this promble too
 so how do u slove it @ https://github.com/mrttson @mrttson

**Comment by xpconanfan** [comment]
The original error indicates an inherent problem on your device or account, which is unrelated to this lib

**Comment by yiantong** [comment]
get it
